import { Platform } from "react-native";

export class StaticBufferValues {
    static random8BitArrayGenerate() : Uint8Array {
		const randomStrings = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split('').map( v => v.charCodeAt(0) );
		const bytesStrings : number[] = [];

		for( let i = 0; i < 3 ; i++ ) {
			bytesStrings.push(randomStrings[Math.floor(Math.random() * randomStrings.length)])
		}

		return Uint8Array.from(bytesStrings);
	}

	static textRecodeGenerate() : Uint8Array {
		const endpointId = StaticBufferValues.random8BitArrayGenerate();

		return Uint8Array.from([
			0x23, 
			endpointId[0], endpointId[1], endpointId[2], endpointId[3],
			0xFC, 0x9F, 0x5E,
			0, 0
		]);
	}

	static get deviceType() : number {
		const device = Platform.OS;
		switch( device ) {
			case "android" : return 0x01;
			case "ios" : return 0x01;
			case "macos" : return 0x03;
			case "windows" : return 0x03;
			case "web" : return 0x00;
			default: return 0x00;
		}
	}

	static TXTRecodeValue() : Uint8Array {
		// Generated by Github Copilot :)
		const version = 0;
		const visibility = 0; 
		const deviceType = StaticBufferValues.deviceType; 
		const reserved = 0; 
		const bitField = (version << 5) | (visibility << 4) | (deviceType << 1) | reserved;
	
		// 16バイトのランダムな値を生成
		const randomBytes = new Uint8Array(16);
		for(let i = 0; i < 16; i++) {
			randomBytes[i] = Math.floor(Math.random() * 256);
		}
	
		// ユーザーが見ることができるデバイス名をUTF-8でエンコードし、その長さ（1バイト）をプレフィックスとして追加
		let nameChars = new TextEncoder().encode("Nearby Share Development Device");
		if(nameChars.length > 255) {
			nameChars = nameChars.slice(0, 255);
		}
		const nameLength = nameChars.length;
	
		// すべてを1つのUint8Arrayに結合
		const EndpointInfo = new Uint8Array(1 + 16 + 1 + nameChars.length);
		EndpointInfo[0] = bitField;
		EndpointInfo.set(randomBytes, 1);
		EndpointInfo[17] = nameLength;
		EndpointInfo.set(nameChars, 18);
	
		return EndpointInfo;
	}
}