// #region Imports
import React, { Component } from 'react'
import {
	Platform,
	StyleSheet,
	TouchableOpacity,
	Text,
	FlatList,
	RefreshControl,
	View,
} from 'react-native'
import { SafeAreaProvider } from 'react-native-safe-area-context';
import SafeAreaView from 'react-native-safe-area-view';
import { Icon, ListItem } from 'react-native-elements'
import Zeroconf, { Service } from 'react-native-zeroconf'
import { BridgeServer } from 'react-native-http-bridge-refurbished';
import { 
	ActivityIndicator, 
	Button as PaperButton 
} from 'react-native-paper';
import DeviceInfo from 'react-native-device-info';

import { Buffer } from 'buffer';

import { Ask } from '../types/airdrop.ask';
import { Discover } from '../types/airdrop.discover';
import { HTTPImageFrom, HTTPImageRequest } from '../types';
import { Context } from '../components/context';
//@ts-ignore

// #endregion
// #region Zeroconf Class Definition

const zeroconf = new Zeroconf()

// #endregion

import { NativeStackScreenProps } from "react-native-screens/lib/typescript/native-stack/types";
type RootStackParamList = {
    デバイスの選択: undefined;
    DetailScreen: undefined;
    LogScreen: undefined;
};

/**
 * アプリのエントリーポイント
 */
export default class App extends Component<NativeStackScreenProps<RootStackParamList, 'デバイスの選択'>> {
    static contextType = Context;
    //@ts-ignore
    context!: React.ContextType<typeof Context>
	/**
	 * Zeroconfのインターバルハンドラ変数	
	 */
	public timeout: NodeJS.Timeout | undefined = void 0

	/**
	 * 使用するポート
	 */
	public AIRDROP_HTTP_PORT = 8771

	/**
	 * HTTPサーバーのインスタンス
	 */
	private __BridgeServer: BridgeServer | null = null

// #region HTTP Client Server
	/**
	 * HTTPサーバーを起動します。
	 * 
	 * @returns 
	 */
	public httpServer() {
		const httpbridge = new BridgeServer("neardrop.local", true)
		httpbridge.listen(this.AIRDROP_HTTP_PORT);

		this.context.logs.push({
			emoji: '🔗',
			message: `Starting HTTP server on port ${this.AIRDROP_HTTP_PORT}`
		})

		httpbridge.get('/info', async ( request, response ) => {
			return ({
				status : "OK",
				data : {
					clientId : DeviceInfo.getUniqueId(),
					clientName : DeviceInfo.getModel(),
					clientModel : Platform.OS
				}
			})
		})

		httpbridge.get('/authorization', async ( request , response ) => {
			
		})

		httpbridge.post("/Discover", async (request, response) => {
			return {
				"ReceiverMediaCapabilities": Buffer.from(JSON.stringify({
					version: 1
				})),
				"ReciverComputerName": "Google Pixel 6a",
				"ReceiverModelName": "Pixel 6a",
			} as Discover
		})

		httpbridge.post<Ask>("/Ask", async (request, response) => {

			const data = request.data
			this.context.senderData = data as Ask

			return {
				"ReceiverComputerName": "Google Pixel 6a",
				"ReceiverModelName": "Pixel 6a"
			} as Ask
		})

		httpbridge.post<string>("/upload", async ( request, response ) => {
			const postJSONData = JSON.parse( JSON.stringify( request.data ) ) as HTTPImageRequest
			console.log( postJSONData.status ) 

			const deviceInfomationfromHash = JSON.parse(
				Buffer.from( postJSONData.from, "base64" ).toString("utf-8")
			) as HTTPImageFrom

			const data = Buffer.from( postJSONData.image )
			this.context.logs.push({
				emoji : "⚠️",
				message : `Received ${data.byteLength} bytes of data from ${deviceInfomationfromHash.name}(${deviceInfomationfromHash.id})`
			})
			this.context.logs.push({
				emoji: '📨',
				message: `Received ${data.byteLength} bytes of data`
			})

			this.context.notification = {
				emoji: '📨',
				message: `Received ${data.byteLength} bytes of data`
			}

			this.context.recivedDatas.push({
				from: postJSONData.from,
				bytes: data.byteLength,
				data: data
			})

			return {
				"status": "OK"
			}
		})

		return httpbridge;
	}

//#endregion

// #region Static Functions
	/**
	 * デバイスの種類を取得します。
	 * 依存しないstaticな関数
	 */
	static get deviceType() : number {
		const device = Platform.OS;
		switch( device ) {
			case "android" : return 1;
			case "ios" : return 1;
			case "macos" : return 3;
			case "windows" : return 3;
			case "web" : return 0;
			default: return 0;
		}
	}

	/**
	 * TXTレコードの値を生成します。 
	 */
	static TXTRecodeValue() : Uint8Array {
		// Generated by Github Copilot :)
		const version = 0;
		const visibility = 0; 
		const deviceType = App.deviceType; 
		const reserved = 0; 
		const bitField = (version << 5) | (visibility << 4) | (deviceType << 1) | reserved;
	
		// 16バイトのランダムな値を生成
		const randomBytes = new Uint8Array(16);
		for(let i = 0; i < 16; i++) {
			randomBytes[i] = Math.floor(Math.random() * 256);
		}
	
		// ユーザーが見ることができるデバイス名をUTF-8でエンコードし、その長さ（1バイト）をプレフィックスとして追加
		let nameChars = new TextEncoder().encode("Nearby Share Development Device");
		if(nameChars.length > 255) {
			nameChars = nameChars.slice(0, 255);
		}
		const nameLength = nameChars.length;
	
		// すべてを1つのUint8Arrayに結合
		const EndpointInfo = new Uint8Array(1 + 16 + 1 + nameChars.length);
		EndpointInfo[0] = bitField;
		EndpointInfo.set(randomBytes, 1);
		EndpointInfo[17] = nameLength;
		EndpointInfo.set(nameChars, 18);
	
		return EndpointInfo;
	}

	


// #endregion

// #region Component Mount
	/**
	 * Reactの関数
	 * コンポーネントがマウントされたときに発火する
	 */
	componentDidMount() {
		// #region mDNS Configuration
		/* HTTPサーバーを起動　*/
		this.__BridgeServer = this.httpServer();
		/* データを初期フェッチ */
		this.refreshData()

		/**
		 * mDNSのTXTレコード
		 */
		const textRecode = App.TXTRecodeValue()

		/* mDNSサービスを開始 */
		zeroconf.publishService(
			/* サービス名 */
			'FC9F5ED42C8A',
			/* プロトコル */
			'tcp',
			/* ドメイン */
			'local.',
			/* ホスト名 */
			Buffer.from( textRecode ).toString('base64'),
			/* 使用ポート */
			5353,
			/* TXTレコード */
			{
				n: Buffer.from(textRecode).toString('base64'),
			}
		)

		console.log(
			`EndpointInfo: ${Buffer.from(textRecode).toString("base64")}`
		)

		//#endregion
		// #region mDNS Event Handlers

		/* mDNSのイベントハンドラ */
		zeroconf.on('start', () => {
			this.context.setObjectState({ isScanning: true })
			this.context.logs.push({
				emoji: '🔍',
				message: 'Started scanning and lunching the mDNS service...'
			})

		})

		zeroconf.on('stop', () => {
			this.context.setObjectState({ isScanning: false })
			this.context.logs.push({
				emoji: '🛑',
				message: 'Stopped scanning'
			})
		})

		zeroconf.on('update', () => {
			this.context.logs.push({
				emoji: '🔄',
				message: 'Updating Data...'
			})
		})

		zeroconf.on('resolved', async service => {
			this.context.logs.push({
				emoji: '🐉',
				message: `Resolved ${service.name} (${service.host})`
			})
			this.context.logs.push({
				emoji: '🔗',
				message: JSON.stringify(service)
			})

			const deviceName = await this.getDeviceName(service)
			if (deviceName !== null) {
				this.context.logs.push({
					emoji: '📱',
					message: `Fetch Success: ${JSON.stringify(deviceName.data.clientId)} -  ${deviceName.data.clientName} (${deviceName.data.clientModel})`
				})
			}

			const newService = Object.assign( service, deviceName !== null ? deviceName.data : {}) as Service & { clientName : string, clientModel : string }

			this.context.setObjectState({
				services: {
					...this.context.services,
					[service.host]: newService,
				},
			})
		})


		zeroconf.on('error', err => {
			this.context.setObjectState({ isScanning: false })
			this.context.logs.push({
				emoji: '🚨',
				message: `Error: ${err}`
			})
		})
	}

	//#endregion
	/**
	 * 
	 * デバイス名を取得する関数。serviceを引数に取り、Promiseを返します。
	 * 
	 * @param {Service} service - サービス情報
	 */
	async getDeviceName( service : Service ) {
		const response = await fetch(`http://${service.host}:${this.AIRDROP_HTTP_PORT}/info`)
		if( response.ok ) {
			const data = await response.json() as { status : string, data : { clientId : string, clientName : string, clientModel : string } };
			return data;
		}

		return null;
	}

	/**
	 * Reactの関数
	 * コンポーネントがアンマウントされたときに発火する
	 */
	componentWillUnmount() {
		this.context.logs.push({
			emoji: '🛑',
			message: 'Unmounting the component and stopping the mDNS service...'
		})

		this.__BridgeServer !== null && this.__BridgeServer.stop()
		zeroconf.stop();
	}

	//#region Components 
	//#region Render

	/**
	 * デバイス一覧のレンダー
	 */
	renderRow = ({ item, index }: { item: string, index: number }) => {
		const { name, fullName, host, addresses, clientModel, clientName } = this.context.services[item]

		return (
			<TouchableOpacity
				onPress={() => {
					this.context.setObjectState({
						selectedService: host,
					});
                    this.props.navigation.navigate('DetailScreen');
                }}
				style={styles.textWithIcon}
			>
				<Icon name="smartphone" size={35} />
				<ListItem.Content>
					<ListItem.Title>{clientName}</ListItem.Title>
					<ListItem.Subtitle>{fullName} / {addresses.join(',')}</ListItem.Subtitle>
				</ListItem.Content>
			</TouchableOpacity>
		)
	}

	// #endregion

	refreshData = () => {
		const { isScanning } = this.context
		if (isScanning) {
			return
		}
		this.context.setObjectState({ services: {} })

		zeroconf.scan('FC9F5ED42C8A', 'tcp', undefined)
		this.context.logs.push({
			emoji: '🔍♻️',
			message: 'ReScanning for services...'
		})

		clearTimeout(this.timeout)
		this.timeout = setTimeout(() => {
			zeroconf.stop()
		}, 5000)
	}

	render() {
		const { services, selectedService, isScanning } = this.context
		console.log(selectedService)

		return (
			<SafeAreaProvider>
				<SafeAreaView style={styles.container}>
					{
						isScanning ? (
							<>
								<View style={styles.textWithIcon}>
									<ActivityIndicator size="small" />
									<Text>付近のデバイスを検索中</Text>
								</View>
							</>
						) : (
							<>
								<FlatList
									data={Object.keys(services)}
									renderItem={this.renderRow}
									keyExtractor={key => key}
									refreshControl={
										<RefreshControl
											refreshing={isScanning}
											onRefresh={this.refreshData}
											tintColor="skyblue"
										/>
									}
								/>
								<PaperButton icon="archive" mode='contained-tonal' onPress={() => this.props.navigation.navigate('LogScreen')}>
									デバックログを確認する
								</PaperButton>
							</>
						)
					}
				</SafeAreaView>
			</SafeAreaProvider>
		)
	}

	//#endregion
}

//#region Styles

const styles = StyleSheet.create({
	udpadding: {
		paddingTop: 10,
		paddingBottom: 10
	},
	textWithIcon: {
		display: 'flex',
		flexDirection: 'row',
		alignContent: 'center',
		alignItems: 'center',
		textAlign: 'center',
		justifyContent: 'center',
		gap: 10,
		fontSize: 30
	},
	textWithIconSizeFree: {
		padding: 10,
		display: 'flex',
		flexDirection: 'row',
		alignContent: 'center',
		alignItems: 'center',
		textAlign: 'center',
		justifyContent: 'center',
		gap: 10,
	},
	container: {
		flex: 1,
        marginTop: 10,
		marginLeft: 10,
		marginRight: 10,
		marginBottom: 10,
	},
	closeButton: {
		padding: 20,
		textAlign: 'center',
	},
	json: {
		padding: 6,
		fontWeight: "bold",
		fontSize: 15,
	},
	logs: {
		padding: 3,
		fontSize: 20,
		fontWeight: "semibold"
	},
	state: {
		fontSize: 20,
		textAlign: 'center',
		margin: 30,
	},
	flexLog: {
		display: 'flex',
		flexDirection: "row",
		alignContent: "center"
	}
})

App.contextType = Context

//#endregion