// #region Imports
import React, { Component } from 'react'
import {
	Platform,
	StyleSheet,
	TouchableOpacity,
	Text,
	FlatList,
	RefreshControl,
	View,
} from 'react-native'
import { SafeAreaProvider } from 'react-native-safe-area-context';
import SafeAreaView from 'react-native-safe-area-view';
import { Icon, ListItem } from 'react-native-elements'
import Zeroconf, { Service } from 'react-native-zeroconf'
import { BridgeServer } from 'react-native-http-bridge-refurbished';
import {
	ActivityIndicator,
	Button as PaperButton
} from 'react-native-paper';
import { Buffer } from 'buffer';
import { NativeStackScreenProps } from "react-native-screens/lib/typescript/native-stack/types";

import { RootStackParamList } from '../types';
import { Context } from '../components/context';
// #endregion


const zeroconf = new Zeroconf()

/**
 * アプリのエントリーポイント
 */
export default class App extends Component<NativeStackScreenProps<RootStackParamList, 'デバイスの選択'>> {
	static contextType = Context;
	//@ts-ignore
	context!: React.ContextType<typeof Context>
	/**
	 * Zeroconfのインターバルハンドラ変数	
	 */
	public timeout: NodeJS.Timeout | undefined = void 0

	/**
	 * 使用するポート
	 */
	public AIRDROP_HTTP_PORT = 8771

	/**
	 * HTTPサーバーのインスタンス
	 */
	private __BridgeServer: BridgeServer | null = null

	// #region Static Functions
	/**
	 * デバイスの種類を取得します。
	 * 依存しないstaticな関数
	 */
	static get deviceType(): number {
		const device = Platform.OS;
		switch (device) {
			case "android": return 1;
			case "ios": return 1;
			case "macos": return 3;
			case "windows": return 3;
			case "web": return 0;
			default: return 0;
		}
	}

	/**
	 * TXTレコードの値を生成します。 
	 */
	static TXTRecodeValue(): Uint8Array {
		// Generated by Github Copilot :)
		const version = 0;
		const visibility = 0;
		const deviceType = App.deviceType;
		const reserved = 0;
		const bitField = (version << 5) | (visibility << 4) | (deviceType << 1) | reserved;

		// 16バイトのランダムな値を生成
		const randomBytes = new Uint8Array(16);
		for (let i = 0; i < 16; i++) {
			randomBytes[i] = Math.floor(Math.random() * 256);
		}

		// ユーザーが見ることができるデバイス名をUTF-8でエンコードし、その長さ（1バイト）をプレフィックスとして追加
		let nameChars = new TextEncoder().encode("Nearby Share Development Device");
		if (nameChars.length > 255) {
			nameChars = nameChars.slice(0, 255);
		}
		const nameLength = nameChars.length;

		// すべてを1つのUint8Arrayに結合
		const EndpointInfo = new Uint8Array(1 + 16 + 1 + nameChars.length);
		EndpointInfo[0] = bitField;
		EndpointInfo.set(randomBytes, 1);
		EndpointInfo[17] = nameLength;
		EndpointInfo.set(nameChars, 18);

		return EndpointInfo;
	}




	// #endregion

	// #region Component Mount
	/**
	 * Reactの関数
	 * コンポーネントがマウントされたときに発火する
	 */
	componentDidMount() {
		// #region mDNS Configuration
		/* HTTPサーバーを起動　*/

		/* データを初期フェッチ */
		this.refreshData()

		/**
		 * mDNSのTXTレコード
		 */
		const textRecode = App.TXTRecodeValue()

		/* mDNSサービスを開始 */
		zeroconf.publishService(
			/* サービス名 */
			'FC9F5ED42C8A',
			/* プロトコル */
			'tcp',
			/* ドメイン */
			'local.',
			/* ホスト名 */
			Buffer.from(textRecode).toString('base64'),
			/* 使用ポート */
			5353,
			/* TXTレコード */
			{
				n: Buffer.from(textRecode).toString('base64'),
			}
		)

		console.log(
			`EndpointInfo: ${Buffer.from(textRecode).toString("base64")}`
		)

		//#endregion
		// #region mDNS Event Handlers

		/* mDNSのイベントハンドラ */
		zeroconf.on('start', () => {
			this.context.setObjectState({ isScanning: true })
			this.context.logs.push({
				emoji: '🔍',
				message: 'Started scanning and lunching the mDNS service...'
			})

		})

		zeroconf.on('stop', () => {
			this.context.setObjectState({ isScanning: false })
			this.context.logs.push({
				emoji: '🛑',
				message: 'Stopped scanning'
			})
		})

		zeroconf.on('update', () => {
			this.context.logs.push({
				emoji: '🔄',
				message: 'Updating Data...'
			})
		})

		zeroconf.on('resolved', async service => {
			this.context.logs.push({
				emoji: '🐉',
				message: `Resolved ${service.name} (${service.host})`
			})
			this.context.logs.push({
				emoji: '🔗',
				message: JSON.stringify(service)
			})

			const deviceName = await this.getDeviceName(service)
			if (deviceName !== null) {
				this.context.logs.push({
					emoji: '📱',
					message: `Fetch Success: ${JSON.stringify(deviceName.data.clientId)} -  ${deviceName.data.clientName} (${deviceName.data.clientModel})`
				})
			}

			const newService = Object.assign(service, deviceName !== null ? deviceName.data : {}) as Service & { clientName: string, clientModel: string }

			this.context.setObjectState({
				services: {
					...this.context.services,
					[service.host]: newService,
				},
			})
		})


		zeroconf.on('error', err => {
			this.context.setObjectState({ isScanning: false })
			this.context.logs.push({
				emoji: '🚨',
				message: `Error: ${err}`
			})
		})
	}

	//#endregion
	/**
	 * 
	 * デバイス名を取得する関数。serviceを引数に取り、Promiseを返します。
	 * 
	 * @param {Service} service - サービス情報
	 */
	async getDeviceName(service: Service) {
		const response = await fetch(`http://${service.host}:${this.AIRDROP_HTTP_PORT}/info`)
			.catch(err => {
				this.context.logs.push({
					emoji: '🚨',
					message: `Error on getDeviceName : ${err}`
				})
				return null;
			});
		if (response === null) return null;

		if (response.ok) {
			const data = await response.json() as { status: string, data: { clientId: string, clientName: string, clientModel: string } };
			return data;
		}

		return null;
	}

	/**
	 * Reactの関数
	 * コンポーネントがアンマウントされたときに発火する
	 */
	componentWillUnmount() {
		this.context.logs.push({
			emoji: '🛑',
			message: 'Unmounting the component and stopping the mDNS service...'
		})

		this.__BridgeServer !== null && this.__BridgeServer.stop()
		zeroconf.stop();
	}

	//#region Components 
	//#region Render

	/**
	 * デバイス一覧のレンダー
	 */
	renderRow = ({ item, index }: { item: string, index: number }) => {
		const { name, fullName, host, addresses, clientModel, clientName } = this.context.services[item]

		return (
			<TouchableOpacity
				onPress={() => {
					this.context.setObjectState({
						selectedService: host,
					});
					this.props.navigation.navigate('DetailScreen');
				}}
				style={[styles.textWithIcon, styles.upadding]}
			>
				<Icon name="smartphone" size={35} />
				<ListItem.Content>
					<ListItem.Title style={styles.titleButSmall}>{clientName ?? fullName.split('.')[0]}</ListItem.Title>
					<ListItem.Subtitle>{fullName} / {addresses.join(',')}</ListItem.Subtitle>
				</ListItem.Content>
			</TouchableOpacity>	
		)
	}

	// #endregion

	refreshData = () => {
		const { isScanning } = this.context
		if (isScanning) {
			return
		}
		this.context.setObjectState({ services: {} })

		zeroconf.scan('FC9F5ED42C8A', 'tcp', 'local.')
		this.context.logs.push({
			emoji: '🔍♻️',
			message: 'ReScanning for services...'
		})

		clearTimeout(this.timeout)
		this.timeout = setTimeout(() => {
			zeroconf.stop()
		}, 5000)
	}

	render() {
		const { services, selectedService, isScanning } = this.context

		return (
			<SafeAreaProvider>
				<SafeAreaView style={styles.container}>
					<Text style={styles.title}> NearDrop </Text>
					<View style={styles.flexColumn}>
						<Text style={styles.udpadding}>検出されたデバイス一覧</Text>
						{
							isScanning ? (
								<>
									<View style={styles.textWithIconNotBackground}>
										<ActivityIndicator size="small" />
										<Text>付近のデバイスを検索中</Text>
									</View>
								</>
							) : (
								<>
									<FlatList
										data={Object.keys(services)}
										renderItem={this.renderRow}
										keyExtractor={key => key}
										refreshControl={
											<RefreshControl
												refreshing={isScanning}
												onRefresh={this.refreshData}
												tintColor="skyblue"
											/>
										}
									/>
								</>
							)
						}
					</View>
					<View style={styles.udpadding}>
					{ !isScanning && (
						<View style={styles.flexColumn}>
							<PaperButton icon="image" mode='contained-tonal' onPress={() => this.props.navigation.navigate("写真の保存")}>
								写真を見る
							</PaperButton>
							<PaperButton icon="reload" mode='contained-tonal' onPress={() => this.refreshData()}>
								リロードする
							</PaperButton>
							<PaperButton icon="archive" mode='contained-tonal' onPress={() => this.props.navigation.navigate('LogScreen')}>
								デバックログを確認する
							</PaperButton>
						</View>
					)}
					</View>
				</SafeAreaView>
			</SafeAreaProvider>
		)
	}

	//#endregion
}

//#region Styles

const styles = StyleSheet.create({
	title: {
		fontSize: 30,
		paddingTop: 10,
		paddingBottom: 10,
	},
	titleButSmall: {
		fontSize: 20,
	},
	flexColumn: {
		display: 'flex',
		flexDirection: 'column',
		gap: 10
	},
	upadding: {
		paddingTop: 10,
	},
	udpadding: {
		paddingTop: 10,
		paddingBottom: 10
	},
	textWithIconNotBackground: {
		display: 'flex',
		flexDirection: 'row',
		alignContent: 'center',
		alignItems: 'center',
		textAlign: 'center',
		justifyContent: 'center',
		gap: 10,
		fontSize: 30,
	},
	textWithIcon: {
		display: 'flex',
		flexDirection: 'row',
		alignContent: 'center',
		alignItems: 'center',
		textAlign: 'center',
		justifyContent: 'center',
		gap: 10,
		fontSize: 30,
		padding: 10,
		backgroundColor: '#f0f0f0',
		borderRadius: 10
	},

	textWithIconSizeFree: {
		padding: 10,
		display: 'flex',
		flexDirection: 'row',
		alignContent: 'center',
		alignItems: 'center',
		textAlign: 'center',
		justifyContent: 'center',
		gap: 10,
	},
	container: {
		flex: 1,
		marginTop: 10,
		marginLeft: 10,
		marginRight: 10,
		marginBottom: 10,
	},
	closeButton: {
		padding: 20,
		textAlign: 'center',
	},
	json: {
		padding: 6,
		fontWeight: "bold",
		fontSize: 15,
	},
	logs: {
		padding: 3,
		fontSize: 20,
		fontWeight: "semibold"
	},
	state: {
		fontSize: 20,
		textAlign: 'center',
		margin: 30,
	},
	flexLog: {
		display: 'flex',
		flexDirection: "row",
		alignContent: "center"
	}
})

App.contextType = Context

//#endregion